### ISSUE TITLE
部分手机过几秒就会停止推流

### ISSUE THREAD

**Issue by Darryl-No1** [shenbengit/WebRTC-SRS#10]
使用几台华为手机测试，都出现了过几秒会停止推流的情况，即没有上传的网速，使用一台小米测试机就没出现停止推流情况，作者可知道哪里的问题？

**Comment by shenbengit** [comment]
看下有无报错日志，看下编码器使用的是不是(OMX.hisi.video.encoder.avc)，webrtc对海思编码器兼容性有问题，不行用软编码方式。https://github.com/shenbengit/WebRTCExtension/issues/1

**Comment by Darryl-No1** [comment]
> 看下有无报错日志，看下编码器使用的是不是(OMX.hisi.video.encoder.avc)，webrtc对海思编码器兼容性有问题，不行用软编码方式。[shenbengit/WebRTCExtension#1](https://github.com/shenbengit/WebRTCExtension/issues/1)

有问题的确实都是海思芯片，没有任何报错，反复对比了与小米的日志，就是有问题的手机日志会多这么一句  W/ACodec: forcing OMX state to Idle when received shutdown in ExecutingState

**Comment by Darryl-No1** [comment]
使用了软编码，效果不好会卡顿，但也算是个解决的办法

**Comment by shenbengit** [comment]
目前现在的手机性能一般都够，调低分辨率、帧率。

**Comment by kbxwn** [comment]
可以尝试在HardwareVideoEncoder 类的public VideoCodecStatus encode(VideoFrame videoFrame, EncodeInfo encodeInfo) 方法里，修改丢帧时重置编解码器，用P40测试可以持续推流
if (outputBuilders.size() > MAX_ENCODER_Q_SIZE) {
            // Too many frames in the encoder.  Drop this frame.
            Logging.e(TAG, "Dropped frame, encoder queue full, " + outputBuilders.size() + " > " + MAX_ENCODER_Q_SIZE);
            VideoCodecStatus status = resetCodec(frameWidth, frameHeight, shouldUseSurfaceMode);
            if (status != VideoCodecStatus.OK) {
                return status;
            }
            return VideoCodecStatus.NO_OUTPUT; // See webrtc bug 2887.
        }

**Comment by ax3726** [comment]
> 可以尝试在HardwareVideoEncoder 类的public VideoCodecStatus encode(VideoFrame videoFrame, EncodeInfo encodeInfo) 方法里，修改丢帧时重置编解码器，用P40测试可以持续推流 if (outputBuilders.size() > MAX_ENCODER_Q_SIZE) { // Too many frames in the encoder. Drop this frame. Logging.e(TAG, "Dropped frame, encoder queue full, " + outputBuilders.size() + " > " + MAX_ENCODER_Q_SIZE); VideoCodecStatus status = resetCodec(frameWidth, frameHeight, shouldUseSurfaceMode); if (status != VideoCodecStatus.OK) { return status; } return VideoCodecStatus.NO_OUTPUT; // See webrtc bug 2887. }

感谢提供思路，但目前又遇到另一个问题，在华为擎云c5e平板上运行在重置编码器时会偶现异常，导致编码器无法正常工作了
E  [OMX.qcom.video.encoder.avc] failed to set input port definition parameters.
2024-04-25 15:13:47.874 14519-20531 ACodec                  com.shencoder.webrtc_srs.push        E  [OMX.qcom.video.encoder.avc] configureCodec returning error -12
2024-04-25 15:13:47.874 14519-20531 ACodec                  com.shencoder.webrtc_srs.push        E  signalError(omxError 0x80001001, internalError -12)
2024-04-25 15:13:47.874 14519-20530 MediaCodec              com.shencoder.webrtc_srs.push        E  Codec reported err 0xfffffff4, actionCode 0, while in state 3/CONFIGURING
2024-04-25 15:13:47.874 14519-20530 MediaCodec              com.shencoder.webrtc_srs.push        D  flushMediametrics
2024-04-25 15:13:47.887 14519-14662 org.webrtc.Logging      com.shencoder.webrtc_srs.push        E  HardwareVideoEncoder: initEncodeInternal failed
2024-04-25 15:13:47.888 14519-14662 org.webrtc.Logging      com.shencoder.webrtc_srs.push        E  HardwareVideoEncoder: android.media.MediaCodec$CodecException: Error 0xfffffff4
2024-04-25 15:13:47.889 14519-14662 org.webrtc.Logging      com.shencoder.webrtc_srs.push        E  HardwareVideoEncoder: android.media.MediaCodec$CodecException: Error 0xfffffff4
                                                                                                    	at android.media.MediaCodec.native_configure(Native Method)
                                                                                                    	at android.media.MediaCodec.configure(MediaCodec.java:2176)
                                                                                                    	at android.media.MediaCodec.configure(MediaCodec.java:2092)
                                                                                                    	at org.webrtc.MediaCodecWrapperFactoryImpl$MediaCodecWrapperImpl.configure(MediaCodecWrapperFactoryImpl.java:36)
                                                                                                    	at org.webrtc.HardwareVideoEncoder.initEncodeInternal(HardwareVideoEncoder.java:276)
                                                                                                    	at org.webrtc.HardwareVideoEncoder.resetCodec(HardwareVideoEncoder.java:553)
                                                                                                    	at org.webrtc.HardwareVideoEncoder.encode(HardwareVideoEncoder.java:378)
